Min/max relations
rosberry/Framezilla pull request #9
Opened 2020-02-13 12:24 UTC by stason314

Added convenience method for finding max and min between  two relations. Also convenience size configuration with `CGSize`.

2020-02-13 13:44 UTC, artemnovichkov requested changes

2020-02-13 13:44 UTC, artemnovichkov commented on Framezilla.xcodeproj/project.pbxproj
> +		};
Please, remove it

2020-02-13 13:44 UTC, artemnovichkov commented on Sources/Maker+Relations.swift
> +    /// - parameter lhs:   The left hand side relation to campare.
```suggestion
    /// - parameter lhs:   The left hand side relation to compare.
```

2020-02-13 13:44 UTC, artemnovichkov commented on Sources/Maker+Relations.swift
> +    /// - parameter rhs:   The right hand side relation to campare.
```suggestion
    /// - parameter rhs:   The right hand side relation to compare.
```

2020-02-13 13:44 UTC, artemnovichkov commented on Sources/Maker+Relations.swift
> +    /// - parameter rhs:   The right hand side relation to campare.
compare

2020-02-13 13:44 UTC, artemnovichkov commented on Sources/UIView+Relations.swift
> +/// Phantom type for `nui_height`, `nui_widht` relations.
```suggestion
/// Phantom type for `nui_height`, `nui_width` relations.
```

2020-02-13 13:44 UTC, artemnovichkov commented on Sources/Maker+Relations.swift
> +        return lhsConvertedValue > rhsConvertedValue ? lhs : rhs
```suggestion
        return max(lhsConvertedValue, rhsConvertedValue)
```

2020-02-13 13:44 UTC, artemnovichkov commented on Sources/Maker+Relations.swift
> +        return lhsConvertedValue < rhsConvertedValue ? lhs : rhs
```suggestion
        return min(lhsConvertedValue, rhsConvertedValue)
```

2020-02-13 13:44 UTC, artemnovichkov commented on Sources/Maker.swift
> +    }
I don't see any tests for this logic

2020-02-14 03:51 UTC, artemnovichkov requested changes

2020-02-14 03:51 UTC, artemnovichkov commented on Tests/MakerTests.swift
> +    }
Please split this test in two separate tests

2020-02-14 03:53 UTC, artemnovichkov approved these changes

2020-02-14 04:29 UTC, ghost approved these changes

2020-02-14 04:29 UTC, rosberry commented on Sources/Maker+Relations.swift
> +    func maxRelation<Relation>(_ lhs: RelationView<Relation>, _ rhs: RelationView<Relation>) -> RelationView<Relation> {
```suggestion
    func max<Relation>(_ lhs: RelationView<Relation>, _ rhs: RelationView<Relation>) -> RelationView<Relation> {
```

2020-02-14 04:29 UTC, rosberry commented on Sources/Maker+Relations.swift
> +    func minRelation<Relation>(_ lhs: RelationView<Relation>, _ rhs: RelationView<Relation>) -> RelationView<Relation> {
```suggestion
    func min<Relation>(_ lhs: RelationView<Relation>, _ rhs: RelationView<Relation>) -> RelationView<Relation> {
```

2020-02-14 04:34 UTC, ntunin approved these changes

2020-02-14 04:49 UTC, merged